; Script generated by the Inno Setup Script Wizard.
#define MyAppName "R-LINK-DORCO"         
#define MyAppVersion "1.0.0.3"
#define MyAppPublisher "Rynan Technologies"
#define MyAppURL "https://rynantech.com/"
#define MyAppExeName "BarcodeVerificationSystem.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
#define MyAppDateTimeRelease "260619_0835"

[Setup]
; 2. QUAN TRỌNG: Bạn phải bấm Tools -> Generate GUID để lấy mã mới cho mỗi App khác nhau
; Không được dùng chung mã {51AA0210...} của R-LINK
AppId={{F15777D3-47BF-4D9B-9BF8-212AAC7C9601}

AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

; 3. QUAN TRỌNG: DefaultDirName sẽ tạo thư mục riêng theo MyAppName
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayName={#MyAppName} 
ChangesAssociations=yes
DisableProgramGroupPage=yes
UninstallDisplayIcon={app}\icon.ico 
OutputDir=SoftwareInstaller
OutputBaseFilename=R_Link_DORCO_Setup64_{#MyAppVersion}_{#MyAppDateTimeRelease}
SetupIconFile=icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Đảm bảo đường dẫn nguồn (Source) trỏ đúng vào folder build của dự án tương ứng
Source: "bin\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\BarcodeVerificationSystem.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "bin\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "*.pdb";
Source: "vcredist2010_x86.exe"; DestDir: "{tmp}"; Flags: ignoreversion; Check: not IsVCRedistInstalled
Source: "icon.ico"; DestDir: "{app}"; Flags: ignoreversion  

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKLM; Subkey: "Software\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}"; ValueType: string; ValueName: "DisplayIcon"; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletevalue

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"

[Run]
Filename: "{tmp}\vcredist2010_x86.exe"; Parameters: "/install /quiet /norestart"; Check: not IsVCRedistInstalled; StatusMsg: "Installing VCRedist..."
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: postinstall shellexec runasoriginaluser

[Code]
// Kiểm tra VCRedist đã cài chưa
function IsVCRedistInstalled(): Boolean;
var
  Installed: Cardinal;
begin
  if RegQueryDWordValue(HKLM, 'SOFTWARE\WOW6432Node\Microsoft\VisualStudio\10.0\VC\VCRedist\x86', 'Installed', Installed) then
    Result := (Installed = 1)
  else
    Result := False;
end;